apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-es-sec
  namespace: app
spec:
  refreshInterval: 1h  # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-cluster-secret-store # name of cluster secret store
  target:
    name: app-sec    # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
  - secretKey: PASSWORD # name of secret in secret file
    remoteRef:
      key: PASSWORD  # name of the GCPSM secret key